In [1]:
tup = 1,2,3  # Defines a tuple with 3 values

print(tup)

(1, 2, 3)

In [2]:
tup = (1,2,3) # Can also be defined this way. Sometimes offers better readability

print(tup)

(1, 2, 3)

In [3]:
tup_nested = (1,2,3),(4,5) #This is a nested tuple

print(tup_nested)

((1, 2, 3), (4, 5))

The above example shows how one tuple can be included in another tuple. This is perfectly normal in Python as a tuple can store an object of any type, including an object of type tuple itself.

One can also convert any sequence into a tuple.

In [4]:
tup = tuple([1,2,3])

print(tup)

(1, 2, 3)

The above example shows converting an array in a tuple.

A string in general is also a sequence of characters. It can be converted into a tuple too, just as any other sequence.

In [5]:
tup = tuple('hello')

print(tup)

('h', 'e', 'l', 'l', 'o')

How do you access elements of a Tuple? We do it just like any other sequence type.

In [6]:
tup[0]

'h'

Indexes in Python start from `0` like most other programming languages. So `tup[0]` gets us the first element in tuple.

A tuple does not necessarily have to be homogeneous. It can be hetrogeneous in nature. This means it can store objects of different types.

In [7]:
tup = 'hello', [1,2,3], (4,5,6), True

print(tup)

('hello', [1, 2, 3], (4, 5, 6), True)

In [8]:
tup = tuple(['hello', [1,2,3], (4,5,6), True]) #Also written as this

print(tup)

('hello', [1, 2, 3], (4, 5, 6), True)

A tuple itself is immutable, but if an object inside a tuple is mutable, it can be done so by directly mutating the object in-place.

In [9]:
tup[1].append(4)

print(tup)

('hello', [1, 2, 3, 4], (4, 5, 6), True)

However, `tup[2].append(4)` would now work, as at index 2 we have a tuple. Index 1 was an array / list so the append operation worked.

## Concatenating Tuples

While tuples by themselves are immutable, we can concatenate two different tuples to make longer tuples.

In [10]:
tup1 = 1,2,3
tup2 = 4,5,6

tup3 = tup1 + tup2

print(tup3)

(1, 2, 3, 4, 5, 6)

By using just the `+` operator, you can concatenate tuples to create a longer tuple.

## Multiplying Tuples

One can multiple the tuple to create a large tuple.

In [11]:
tup = 1,2
tup = tup * 4

print(tup)

(1, 2, 1, 2, 1, 2, 1, 2)

We can see that multiplying the tuple by 4, we have caused the tuple to expand itself into 4 times its original size. All values inside the tuple get replicated 4 times with this operation.

## Unpacking Tuples
In a single line of code, we can extract all the values present within the tuple.

In [12]:
tup = 1,2,3

a,b,c = tup #Unpacks the Tuple

print(a)
print(b)
print(c)

1
2
3

In [13]:
print('First index of 1:', tup.index(1))
print('First index of 2:', tup.index(2))
print('First index of 3:', tup.index(3))

First index of 1: 0
First index of 2: 1
First index of 3: 2